apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sleepr
spec:
  ingressClassName: "gce"
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-http
            port:
              number: 80
