apiVersion: v1
kind: Service
metadata:
  name: notifications-service-tcp
spec:
  type: NodePort
  selector:
    app: notifications
    version: v1.0
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
