apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  selector:
    matchLabels:
      app: payments
      version: v1.0
  replicas: 1
  template:
    metadata:
      labels:
        app: payments
        version: v1.0
    spec:
      containers:
      - name: production
        image: "us-central1-docker.pkg.dev/reservation-test-402716/payments/production"
        env:
        - name: PORT
          value: '3001'
        - name: NOTIFICATIONS_HOST
          value: notifications
        - name: NOTIFICATIONS_PORT
          value: '3000'
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe
              key: apiKey
        ports:
        - containerPort: 3001
