apiVersion: v1
kind: Service
metadata:
  name: payments-service-tcp
spec:
  type: NodePort
  selector:
    app: payments
    version: v1.0
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
