apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
spec:
  selector:
    matchLabels:
      app: reservations
      version: v1.0
  replicas: 1
  template:
    metadata:
      labels:
        app: reservations
        version: v1.0
    spec:
      containers:
      - name: production
        image: "us-central1-docker.pkg.dev/reservation-test-402716/reservations/production"
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: connectionString
        - name: HTTP_PORT
          value: '3004'
        - name: AUTH_PORT
          value: '3002'
        - name: AUTH_HOST
          value: 'auth-tcp'
        - name: PAYMENTS_PORT
          value: '3001'
        - name: PAYMENTS_HOST
          value: 'payments'
        ports:
        - containerPort: 3004
