apiVersion: v1
kind: Service
metadata:
  name: reservations-service-http
spec:
  type: NodePort
  selector:
    app: reservations
    version: v1.0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3004
